In [10]:
text="hello! World this is FUTURE INnovation"
text_lower=text.lower()
print(text_lower)

hello! world this is future innovation


In [11]:
import re

text="hello! World this is FUTURE INnovation"
text_clean=re.sub(r'[^a-zA-Z\s]','',text)
print(text_clean)

hello World this is FUTURE INnovation


In [12]:
import nltk
from nltk.corpus import stopwords

nltk.download('stopwords', quiet=True)

stop_word=set(stopwords.words('english'))

text="hello! World this is FUTURE INnovation"
token=[]

for word in text.split():
    if word.lower() not in stop_word:
        token.append(word)

print(token)

['hello!', 'World', 'FUTURE', 'INnovation']


In [13]:
import nltk
from nltk.tokenize import word_tokenize

nltk.download('punkt', quiet=True)
nltk.download('punkt_tab', quiet=True)

text="hello! World this is FUTURE INnovation"

basic=text.split()
print(basic)

token=word_tokenize(text.lower())
print(token)

['hello!', 'World', 'this', 'is', 'FUTURE', 'INnovation']
['hello', '!', 'world', 'this', 'is', 'future', 'innovation']


In [14]:
import nltk
from nltk.stem import PorterStemmer,WordNetLemmatizer
nltk.download('wordnet',quiet=True)
stemmer=PorterStemmer()
lemmatizer=WordNetLemmatizer()
words=['running','gaming','ibrahim']
for word in words:
  stem = stemmer.stem(word)
  lemma = lemmatizer.lemmatize(word,pos='v')
  print(f"Word: {word:12}, Stem: {stem:10}, Lemma: {lemma}")

Word: running     , Stem: run       , Lemma: run
Word: gaming      , Stem: game      , Lemma: game
Word: ibrahim     , Stem: ibrahim   , Lemma: ibrahim


In [15]:
import nltk
import re
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
nltk.download('stopwords', quiet=True)
nltk.download('wordnet', quiet=True)
nltk.download('punkt', quiet=True)
stop_words=set(stopwords.words('english'))
lemmatizer=WordNetLemmatizer()
def preprocess(text):
  text = text.lower()
  text=re.sub(r'[^a-z ]',' ',text)
  filter_token=[]
  for w in token:
    if w not in stop_words:
      filter_token.append(w)
  tokens=filter_token
  lemmatized_token=[]
  for w in tokens:
    lemmatized_token.append(lemmatizer.lemmatize(w))
  tokens=lemmatized_token
  return tokens
text="hello! World  this iS futureINNoveation"
print(preprocess(text))

['hello', '!', 'world', 'future', 'innovation']


In [16]:
from sklearn.feature_extraction.text import CountVectorizer
email={
    'cricket match cricket match ',
    'free win money free  win money',
    'cricket match free win money cricket'
}
cv=CountVectorizer()
x=cv.fit_transform(email).toarray()
print('vocabullary: ',cv.get_feature_names_out())
print(x)


vocabullary:  ['cricket' 'free' 'match' 'money' 'win']
[[2 1 1 1 1]
 [0 2 0 2 2]
 [2 0 2 0 0]]


In [17]:
from sklearn.feature_extraction.text import TfidfVectorizer
email={
    'cricket match cricket match ',
    'free win money free  win money',
    'cricket match free win money cricket'
}
tfidf=TfidfVectorizer( sublinear_tf=True,max_df=0.95,min_df=1)
x=tfidf.fit_transform(email).toarray()
print('feature names: ',tfidf.get_feature_names_out())
print('tfidf matrix')
import numpy as np
print(np.round(x,3))


feature names:  ['cricket' 'free' 'match' 'money' 'win']
tfidf matrix
[[0.646 0.382 0.382 0.382 0.382]
 [0.    0.577 0.    0.577 0.577]
 [0.707 0.    0.707 0.    0.   ]]
